### ISSUE TITLE
STATA - Dimensionality Issue

### ISSUE THREAD

**Issue by Rturati** [zhangxiang0822/ShiftShareSEStata#1]
Dear authors,

First of all, thank you for your research, and for providing codes associated to your methods.

I tried to implement your methodology to compute the right CI of the estimates, however given my dataset (around 48,000 observations) STATA is unable to run it, since the maximum matsize of STATA is 11000. I tried with both an SE and MP version of STATA. 

Do you have in mind a way to solve it/suggestion on how to overcome this issue? 

Thank you in advance for your help and work!
Best
Riccardo

**Comment by xiangzhang-econ** [comment]
Hi Riccardo, @Rturati

What you point out makes perfect sense - as we rely on Stata matrix operation to compute AKM SE, it is infeasible when there're more than 11000 observations. We would update our code in the near future to use regression commands, instead of the matrix operation, to compute AKM SE in our Stata package. For now, I would suggest you use the R/ Matlab version to do the estimation. You could do all data cleaning work in Stata first, and switch to R/Matlab code for AKM SE computation. This can be very inconvenient, but for now, it's the only option. Thanks!

Xiang
