### ISSUE TITLE
Hi Xiang,

### ISSUE THREAD

**Issue by krogerkai** [zhangxiang0822/ShiftShareSEStata#4]
Thanks a lot for your work and the code you provided! I am new to the paper and to the AKM standard errors and trying to implement it in our application. When reading through the paper, I couldn't see any notes on the "derived share" provided in the application. By description, I thought this is just the usual employment shares used to construct the shift-share shocks. This means that in ADH application, there are only 396 4-digit sectors, but the application says 770 sectors. I think I may have missed something while reading through the paper. Could you give me some pointers?

In our application, the employment shares for each region sum to 1. The solution provided in Stata code seems a bit strange, given that in the paper, there is no constraint regarding the sum of the share. If you know some pointers on on this, I would appreciate that as well.

Thanks a lot for your help!
Hoang

**Comment by xiangzhang-econ** [comment]
Hi Hoang, 

Thanks. One thing you may have noticed is that, the ADH application actually used both the changes during 1990 and 2000 and post-2000. Since it is a panel, implementation really requires sector-period pairs. It is as if you have a separate sector in each period. We have section in the paper about panel regressions. It should clarify this. 

With 396 sectors, this would lead to 792 “units” for the shift-share construction. The problem is that we have to drop quasi-collinear units to implement the estimation strategy. The matlab replication code has a function to do that. This is why we have 770 sectors.

Hope this is helpful. Thanks!
